insert into words(russian, english, partofspeech, url)  values('аист', 'stork', 'NOUN', 'stork320.png');
insert into words(russian, english, partofspeech, url)  values('альбатрос', 'albatross', 'NOUN', 'albatross320.png');
insert into words(russian, english, partofspeech, url)  values('баклан', 'cormorant', 'NOUN', 'cormorant320.png');
insert into words(russian, english, partofspeech, url)  values('бекас', 'snipe', 'NOUN', 'snipe320.png');
insert into words(russian, english, partofspeech, url)  values('беркут', 'golden eagle', 'NOUN', 'goldeneagle320.png');
insert into words(russian, english, partofspeech, url)  values('вальдшнеп', 'woodcock', 'NOUN', 'woodcock320.png');
insert into words(russian, english, partofspeech, url)  values('воробей', 'sparrow', 'NOUN', 'sparrow320.png');
insert into words(russian, english, partofspeech, url)  values('ворон', 'raven', 'NOUN', 'raven320.png');
insert into words(russian, english, partofspeech, url)  values('ворона', 'crow', 'NOUN', 'crow320.png');
insert into words(russian, english, partofspeech, url)  values('выпь', 'bittern', 'NOUN', 'bittern320.png');
insert into words(russian, english, partofspeech, url)  values('гагара', 'loon eagle, diver', 'NOUN', 'diver320.png');
insert into words(russian, english, partofspeech, url)  values('галка', 'jackdaw, daw', 'NOUN', 'jackdaw320.png');
insert into words(russian, english, partofspeech, url)  values('глухарь', 'cock of the wood, wood grouse', 'NOUN', 'woodgrouse320.png');
insert into words(russian, english, partofspeech, url)  values('гоголь', 'goldeneye', 'NOUN', 'goldeneye320.png');
insert into words(russian, english, partofspeech, url)  values('голубь', 'pigeon', 'NOUN', 'pigeon320.png');
insert into words(russian, english, partofspeech, url)  values('горлица', 'turtle-dove', 'NOUN', 'turtledove320');
insert into words(russian, english, partofspeech, url)  values('грач', 'rook', 'NOUN', 'rook320.png');
insert into words(russian, english, partofspeech, url)  values('гусь', 'goose', 'NOUN', 'goose320.png');
insert into words(russian, english, partofspeech, url)  values('дрозд', 'thrush', 'NOUN', 'thrush320.png');
insert into words(russian, english, partofspeech, url)  values('дятел', 'woodpecker', 'NOUN', 'woodpecker320.png');
insert into words(russian, english, partofspeech, url)  values('жаворонок', 'lark', 'NOUN', 'lark320.png');
insert into words(russian, english, partofspeech, url)  values('журавль', 'crane', 'NOUN', 'crane320.png');
insert into words(russian, english, partofspeech, url)  values('зимородок', 'halcyon, kingfisher', 'NOUN', 'halcyon320.png');
insert into words(russian, english, partofspeech, url)  values('зяблик', 'chaffinch', 'NOUN', 'chaffinch320.png');
insert into words(russian, english, partofspeech, url)  values('иволга', 'oriole', 'NOUN', 'oriole320.png');
insert into words(russian, english, partofspeech, url)  values('индейка', 'turkey', 'NOUN', 'turkey320.png');
insert into words(russian, english, partofspeech, url)  values('канарейка', 'canary', 'NOUN', 'canary320.png');
insert into words(russian, english, partofspeech, url)  values('клёст', 'crossbill', 'NOUN', 'crossbill320.png');
insert into words(russian, english, partofspeech, url)  values('козодой', 'dorhawk, nightjar', 'NOUN', 'nightjar320.png');
insert into words(russian, english, partofspeech, url)  values('колибри', 'hummingbird', 'NOUN', 'hummingbird320.png');
insert into words(russian, english, partofspeech, url)  values('коноплянка', 'linnet', 'NOUN', 'linnet320.png');
insert into words(russian, english, partofspeech, url)  values('королек', 'regulus', 'NOUN', 'regulus320.png');
insert into words(russian, english, partofspeech, url)  values('коростель', 'landrail, corn crake', 'NOUN', 'landrail320.png');
insert into words(russian, english, partofspeech, url)  values('коршун', 'kite', 'NOUN', 'kite320.png');
insert into words(russian, english, partofspeech, url)  values('кряква', 'wild duck, mallard', 'NOUN', 'mallard320.png');
insert into words(russian, english, partofspeech, url)  values('кукушка', 'cuckoo', 'NOUN', 'cuckoo.png');
insert into words(russian, english, partofspeech, url)  values('кулик', 'sandpiper', 'NOUN', 'sandpiper320.png');
insert into words(russian, english, partofspeech, url)  values('курица', 'hen', 'NOUN', 'hen320.png');
insert into words(russian, english, partofspeech, url)  values('куропатка (серая)', 'partridge(серая)', 'NOUN', 'partridge320.png');
insert into words(russian, english, partofspeech, url)  values('куропатка (белая)', 'willow grouse (белая)', 'NOUN', 'willowgrouse320.png');
insert into words(russian, english, partofspeech, url)  values('ласточка', 'swallow', 'NOUN', 'swallow320.png');
insert into words(russian, english, partofspeech, url)  values('лебедь', 'swan', 'NOUN', 'swan320.png');
insert into words(russian, english, partofspeech, url)  values('лебедь (самец)', 'cob, cob-swan', 'NOUN', 'swan320.png');
insert into words(russian, english, partofspeech, url)  values('малиновка', 'robin, redbreast', 'NOUN', 'robin320.png');
insert into words(russian, english, partofspeech, url)  values('мухоловка', 'flycatcher', 'NOUN', 'flycatcher320.png');
insert into words(russian, english, partofspeech, url)  values('неясыть', 'tawny owl', 'NOUN', 'tawnyowl320.png');
insert into words(russian, english, partofspeech, url)  values('нырок', 'pochard', 'NOUN', 'pochard320.png');
insert into words(russian, english, partofspeech, url)  values('овсянка', '(yellow) banting, yellowhammer', 'NOUN', 'yellowhammer320.png');
insert into words(russian, english, partofspeech, url)  values('оляпка', 'dipper, ouzel', 'NOUN', 'dipper320.png');
insert into words(russian, english, partofspeech, url)  values('орел', 'eagle', 'NOUN', 'eagle320.png');
insert into words(russian, english, partofspeech, url)  values('павлин', 'peacock, peafowl', 'NOUN', 'peacock320.png');
insert into words(russian, english, partofspeech, url)  values('пеночка', 'chiffchaff', 'NOUN', 'chiffchaff320.png');
insert into words(russian, english, partofspeech, url)  values('перепел', 'quail', 'NOUN', 'quail320.png');
insert into words(russian, english, partofspeech, url)  values('петух', 'cock, rooster', 'NOUN', 'rooster320.png');
insert into words(russian, english, partofspeech, url)  values('чибис', 'lapwing, pewit', 'NOUN', 'lapwing320.png' );
insert into words(russian, english, partofspeech, url)  values('пингвин', 'penguin', 'NOUN', 'penguin320.png');
insert into words(russian, english, partofspeech, url)  values('поползень', 'nuthatch', 'NOUN', 'nuthatch320.png');
insert into words(russian, english, partofspeech, url)  values('попугай', 'parrot', 'NOUN', 'parrot320.png');
insert into words(russian, english, partofspeech, url)  values('пустельга', 'kestrel', 'NOUN', 'kestrel320.png');
insert into words(russian, english, partofspeech, url)  values('рябчик', 'hazel grouse, hazel hen', 'NOUN', 'hazelgrouse320.png');
insert into words(russian, english, partofspeech, url)  values('сапсан', 'peregrine', 'NOUN', 'peregrine320.png');
insert into words(russian, english, partofspeech, url)  values('свиристель', 'waxwing', 'NOUN', 'waxwing320.png');
insert into words(russian, english, partofspeech, url)  values('синица', 'tomtit, blue titmouse, blue tit', 'NOUN', 'titmouse320.png' );
insert into words(russian, english, partofspeech, url)  values('скворец', 'starling', 'NOUN', 'starling320.png');
insert into words(russian, english, partofspeech, url)  values('славка', 'whitethroat, warbler', 'NOUN', 'warbler320.png');
insert into words(russian, english, partofspeech, url)  values('снегирь', 'bullfinch', 'NOUN', 'bullfinch320.png');
insert into words(russian, english, partofspeech, url)  values('сова', 'owl', 'NOUN', 'owl320.png');
insert into words(russian, english, partofspeech, url)  values('сойка', 'jay, mockingjay', 'NOUN', 'jay320.png');
insert into words(russian, english, partofspeech, url)  values('соловей', 'nightingale', 'NOUN', 'nightingale320.png');
insert into words(russian, english, partofspeech, url)  values('сорока', 'magpie', 'NOUN', 'magpie320.png');
insert into words(russian, english, partofspeech, url)  values('страус', 'ostrich', 'NOUN', 'ostrich320.png');
insert into words(russian, english, partofspeech, url)  values('стриж', 'swift', 'NOUN', 'swift320.png');
insert into words(russian, english, partofspeech, url)  values('сыч', 'little owl', 'NOUN', 'littleowl320.png');
insert into words(russian, english, partofspeech, url)  values('тетерев', 'black grouse, blackcock', 'NOUN', 'blackcock320.png');
insert into words(russian, english, partofspeech, url)  values('трясогузка', 'wagtail', 'NOUN', 'wagtail320.png');
insert into words(russian, english, partofspeech, url)  values('турухтан', 'ruff', 'NOUN', 'ruffbird320.png');
insert into words(russian, english, partofspeech, url)  values('удод', 'hoopoe', 'NOUN', 'hoopoe320.png');
insert into words(russian, english, partofspeech, url)  values('утка', 'duck', 'NOUN', 'duck320.png');
insert into words(russian, english, partofspeech, url)  values('фазан', 'pheasant', 'NOUN', 'pheasant320.png');
insert into words(russian, english, partofspeech, url)  values('филин', 'eagle-owl', 'NOUN', 'eagleowl320.png');
insert into words(russian, english, partofspeech, url)  values('фламинго', 'flamingo', 'NOUN', 'flamingo320.png');
insert into words(russian, english, partofspeech, url)  values('цапля', 'heron, egret', 'NOUN', 'heron320.png');
insert into words(russian, english, partofspeech, url)  values('цесарка', 'guinea fowl', 'NOUN', 'guineafowl320.png');
insert into words(russian, english, partofspeech, url)  values('чайка', 'gull, sea gull', 'NOUN', 'gull320.png');
insert into words(russian, english, partofspeech, url)  values('чечетка', 'redpoll', 'NOUN', 'redpoll320.png');
insert into words(russian, english, partofspeech, url)  values('чиж', 'siskin', 'NOUN', 'siskin320.png');
insert into words(russian, english, partofspeech, url)  values('чирок', 'teal', 'NOUN', 'teal320.png');
insert into words(russian, english, partofspeech, url)  values('щегол', 'goldfinch', 'NOUN', 'goldfinch320.png');
insert into words(russian, english, partofspeech, url)  values('юрок', 'bramble finch, brambling', 'NOUN', 'brambling320.png');
insert into words(russian, english, partofspeech, url)  values('ястреб', 'hawk', 'NOUN', 'hawk320.png');
commit;

insert into VOCABULARY_WORDS(vocabulary, word) values(1, 1);
insert into VOCABULARY_WORDS(vocabulary, word) values(1, 2);
insert into VOCABULARY_WORDS(vocabulary, word) values(1, 3);
insert into VOCABULARY_WORDS(vocabulary, word) values(1, 4);
insert into VOCABULARY_WORDS(vocabulary, word) values(1, 5);
insert into VOCABULARY_WORDS(vocabulary, word) values(1, 6);
insert into VOCABULARY_WORDS(vocabulary, word) values(1, 7);
insert into VOCABULARY_WORDS(vocabulary, word) values(1, 8);
insert into VOCABULARY_WORDS(vocabulary, word) values(1, 9);
insert into VOCABULARY_WORDS(vocabulary, word) values(1, 10);
insert into VOCABULARY_WORDS(vocabulary, word) values(1, 11);
insert into VOCABULARY_WORDS(vocabulary, word) values(1, 12);
insert into VOCABULARY_WORDS(vocabulary, word) values(1, 13);
insert into VOCABULARY_WORDS(vocabulary, word) values(1, 14);
insert into VOCABULARY_WORDS(vocabulary, word) values(1, 15);
insert into VOCABULARY_WORDS(vocabulary, word) values(1, 16);
insert into VOCABULARY_WORDS(vocabulary, word) values(1, 17);
insert into VOCABULARY_WORDS(vocabulary, word) values(1, 18);
insert into VOCABULARY_WORDS(vocabulary, word) values(1, 19);
insert into VOCABULARY_WORDS(vocabulary, word) values(1, 20);
insert into VOCABULARY_WORDS(vocabulary, word) values(1, 21);
insert into VOCABULARY_WORDS(vocabulary, word) values(1, 22);
insert into VOCABULARY_WORDS(vocabulary, word) values(1, 23);
insert into VOCABULARY_WORDS(vocabulary, word) values(1, 24);
insert into VOCABULARY_WORDS(vocabulary, word) values(1, 25);
insert into VOCABULARY_WORDS(vocabulary, word) values(1, 26);
insert into VOCABULARY_WORDS(vocabulary, word) values(1, 27);
insert into VOCABULARY_WORDS(vocabulary, word) values(1, 28);
insert into VOCABULARY_WORDS(vocabulary, word) values(1, 29);
insert into VOCABULARY_WORDS(vocabulary, word) values(1, 30);
insert into VOCABULARY_WORDS(vocabulary, word) values(1, 31);
insert into VOCABULARY_WORDS(vocabulary, word) values(1, 32);
insert into VOCABULARY_WORDS(vocabulary, word) values(1, 33);
insert into VOCABULARY_WORDS(vocabulary, word) values(1, 34);
insert into VOCABULARY_WORDS(vocabulary, word) values(1, 35);
insert into VOCABULARY_WORDS(vocabulary, word) values(1, 36);
insert into VOCABULARY_WORDS(vocabulary, word) values(1, 37);
insert into VOCABULARY_WORDS(vocabulary, word) values(1, 38);
insert into VOCABULARY_WORDS(vocabulary, word) values(1, 39);
insert into VOCABULARY_WORDS(vocabulary, word) values(1, 40);
insert into VOCABULARY_WORDS(vocabulary, word) values(1, 41);
insert into VOCABULARY_WORDS(vocabulary, word) values(1, 42);
insert into VOCABULARY_WORDS(vocabulary, word) values(1, 43);
insert into VOCABULARY_WORDS(vocabulary, word) values(1, 44);
insert into VOCABULARY_WORDS(vocabulary, word) values(1, 45);
insert into VOCABULARY_WORDS(vocabulary, word) values(1, 46);
insert into VOCABULARY_WORDS(vocabulary, word) values(1, 47);
insert into VOCABULARY_WORDS(vocabulary, word) values(1, 48);
insert into VOCABULARY_WORDS(vocabulary, word) values(1, 49);
insert into VOCABULARY_WORDS(vocabulary, word) values(1, 50);
insert into VOCABULARY_WORDS(vocabulary, word) values(1, 51);
insert into VOCABULARY_WORDS(vocabulary, word) values(1, 52);
insert into VOCABULARY_WORDS(vocabulary, word) values(1, 53);
insert into VOCABULARY_WORDS(vocabulary, word) values(1, 54);
insert into VOCABULARY_WORDS(vocabulary, word) values(1, 55);
insert into VOCABULARY_WORDS(vocabulary, word) values(1, 56);
insert into VOCABULARY_WORDS(vocabulary, word) values(1, 57);
insert into VOCABULARY_WORDS(vocabulary, word) values(1, 58);
insert into VOCABULARY_WORDS(vocabulary, word) values(1, 59);
insert into VOCABULARY_WORDS(vocabulary, word) values(1, 60);
insert into VOCABULARY_WORDS(vocabulary, word) values(1, 61);
insert into VOCABULARY_WORDS(vocabulary, word) values(1, 62);
insert into VOCABULARY_WORDS(vocabulary, word) values(1, 63);
insert into VOCABULARY_WORDS(vocabulary, word) values(1, 64);
insert into VOCABULARY_WORDS(vocabulary, word) values(1, 65);
insert into VOCABULARY_WORDS(vocabulary, word) values(1, 66);
insert into VOCABULARY_WORDS(vocabulary, word) values(1, 67);
insert into VOCABULARY_WORDS(vocabulary, word) values(1, 68);
insert into VOCABULARY_WORDS(vocabulary, word) values(1, 69);
insert into VOCABULARY_WORDS(vocabulary, word) values(1, 70);
insert into VOCABULARY_WORDS(vocabulary, word) values(1, 71);
insert into VOCABULARY_WORDS(vocabulary, word) values(1, 72);
insert into VOCABULARY_WORDS(vocabulary, word) values(1, 73);
insert into VOCABULARY_WORDS(vocabulary, word) values(1, 74);
insert into VOCABULARY_WORDS(vocabulary, word) values(1, 75);
insert into VOCABULARY_WORDS(vocabulary, word) values(1, 76);
insert into VOCABULARY_WORDS(vocabulary, word) values(1, 77);
insert into VOCABULARY_WORDS(vocabulary, word) values(1, 78);
insert into VOCABULARY_WORDS(vocabulary, word) values(1, 79);
insert into VOCABULARY_WORDS(vocabulary, word) values(1, 80);
insert into VOCABULARY_WORDS(vocabulary, word) values(1, 81);
insert into VOCABULARY_WORDS(vocabulary, word) values(1, 82);
insert into VOCABULARY_WORDS(vocabulary, word) values(1, 83);
insert into VOCABULARY_WORDS(vocabulary, word) values(1, 84);
insert into VOCABULARY_WORDS(vocabulary, word) values(1, 85);
insert into VOCABULARY_WORDS(vocabulary, word) values(1, 86);
insert into VOCABULARY_WORDS(vocabulary, word) values(1, 87);
insert into VOCABULARY_WORDS(vocabulary, word) values(1, 88);
insert into VOCABULARY_WORDS(vocabulary, word) values(1, 89);
insert into VOCABULARY_WORDS(vocabulary, word) values(1, 90);

commit;
