insert into words(russian, english, partofspeech, url)  values('акула', 'shark', 'NOUN', 'shark320.png');
insert into words(russian, english, partofspeech, url)  values('барабулька', 'mullus', 'NOUN', 'mullus320.png');
insert into words(russian, english, partofspeech, url)  values('барракуда',	'barracuda', 'NOUN', 'barracuda320.png');
insert into words(russian, english, partofspeech, url)  values('бычок',	'goby', 'NOUN', 'goby320.png');
insert into words(russian, english, partofspeech, url)  values('голавль', 'chub', 'NOUN', 'chub320.png');
insert into words(russian, english, partofspeech, url)  values('горбуша', 'pink salmon', 'NOUN', 'pinksalmon320.png');
insert into words(russian, english, partofspeech, url)  values('ерш', 'ruff', 'NOUN', 'rufffish320.png');
insert into words(russian, english, partofspeech, url)  values('камбала', 'plaice, flounder', 'NOUN', 'plaice320.png');
insert into words(russian, english, partofspeech, url)  values('карп', 'carp', 'NOUN', 'carp320.png');
insert into words(russian, english, partofspeech, url)  values('кефаль', 'mugil', 'NOUN', 'mugil320.png');
insert into words(russian, english, partofspeech, url)  values('лещ', 'bream', 'NOUN', 'bream320.png');
insert into words(russian, english, partofspeech, url)  values('линь', 'tench', 'NOUN', 'tench320.png');
insert into words(russian, english, partofspeech, url)  values('лосось', 'salmon', 'NOUN', 'salmon320.png');
insert into words(russian, english, partofspeech, url)  values('морской окунь', 'seaperch', 'NOUN', 'seaperch320.png');
insert into words(russian, english, partofspeech, url)  values('навага', 'navaga', 'NOUN', 'navaga320.png');
insert into words(russian, english, partofspeech, url)  values('налим',	'burbot', 'NOUN', 'burbot320.png');
insert into words(russian, english, partofspeech, url)  values('окунь',	'perch', 'NOUN', 'perch320.png');
insert into words(russian, english, partofspeech, url)  values('палтус', 'halibut', 'NOUN', 'halibut320.png');
insert into words(russian, english, partofspeech, url)  values('пикша',	'haddock', 'NOUN', 'haddock320.png');
insert into words(russian, english, partofspeech, url)  values('плотва', 'dace', 'NOUN', 'dace320.png');
insert into words(russian, english, partofspeech, url)  values('рыба-меч', 'swordfish', 'NOUN', 'swordfish320.png');
insert into words(russian, english, partofspeech, url)  values('рыба-пила', 'sawfish', 'NOUN', 'sawfish320.png');
insert into words(russian, english, partofspeech, url)  values('сардина', 'sardine', 'NOUN', 'sardine320.png');
insert into words(russian, english, partofspeech, url)  values('сельдь', 'herring', 'NOUN', 'herring320.png');
insert into words(russian, english, partofspeech, url)  values('скат', 'skate', 'NOUN', 'skate320.png');
insert into words(russian, english, partofspeech, url)  values('скумбрия', 'mackerel, scomber', 'NOUN', 'mackerel320.png');
insert into words(russian, english, partofspeech, url)  values('сом', 'catfish', 'NOUN', 'catfish320.png');
insert into words(russian, english, partofspeech, url)  values('стерлядь',	'starlet', 'NOUN', 'starlet320.png');
insert into words(russian, english, partofspeech, url)  values('судак',	'pikeperch, zander', 'NOUN', 'pikeperch320.png');
insert into words(russian, english, partofspeech, url)  values('треска', 'cod', 'NOUN', 'cod320.png');
insert into words(russian, english, partofspeech, url)  values('тунец',	'tuna', 'NOUN', 'tuna320.png');
insert into words(russian, english, partofspeech, url)  values('угорь',	'eel', 'NOUN', 'eel320.png');
insert into words(russian, english, partofspeech, url)  values('форель', 'trout', 'NOUN', 'trout320.png');
insert into words(russian, english, partofspeech, url)  values('хамса',	'anchovy', 'NOUN', 'anchovy320.png');
insert into words(russian, english, partofspeech, url)  values('хариус', 'grayling', 'NOUN', 'grayling320.png');
insert into words(russian, english, partofspeech, url)  values('хек', 'hake,  merluccius', 'NOUN', 'hake320.png');
insert into words(russian, english, partofspeech, url)  values('щука', 'pike', 'NOUN', 'pike320.png');
commit;

insert into VOCABULARY_WORDS(vocabulary, word) values(2, 91);
insert into VOCABULARY_WORDS(vocabulary, word) values(2, 92);
insert into VOCABULARY_WORDS(vocabulary, word) values(2, 93);
insert into VOCABULARY_WORDS(vocabulary, word) values(2, 94);
insert into VOCABULARY_WORDS(vocabulary, word) values(2, 95);
insert into VOCABULARY_WORDS(vocabulary, word) values(2, 96);
insert into VOCABULARY_WORDS(vocabulary, word) values(2, 97);
insert into VOCABULARY_WORDS(vocabulary, word) values(2, 98);
insert into VOCABULARY_WORDS(vocabulary, word) values(2, 99);
insert into VOCABULARY_WORDS(vocabulary, word) values(2, 100);
insert into VOCABULARY_WORDS(vocabulary, word) values(2, 101);
insert into VOCABULARY_WORDS(vocabulary, word) values(2, 102);
insert into VOCABULARY_WORDS(vocabulary, word) values(2, 103);
insert into VOCABULARY_WORDS(vocabulary, word) values(2, 104);
insert into VOCABULARY_WORDS(vocabulary, word) values(2, 105);
insert into VOCABULARY_WORDS(vocabulary, word) values(2, 106);
insert into VOCABULARY_WORDS(vocabulary, word) values(2, 107);
insert into VOCABULARY_WORDS(vocabulary, word) values(2, 108);
insert into VOCABULARY_WORDS(vocabulary, word) values(2, 109);
insert into VOCABULARY_WORDS(vocabulary, word) values(2, 110);
insert into VOCABULARY_WORDS(vocabulary, word) values(2, 111);
insert into VOCABULARY_WORDS(vocabulary, word) values(2, 112);
insert into VOCABULARY_WORDS(vocabulary, word) values(2, 113);
insert into VOCABULARY_WORDS(vocabulary, word) values(2, 114);
insert into VOCABULARY_WORDS(vocabulary, word) values(2, 115);
insert into VOCABULARY_WORDS(vocabulary, word) values(2, 116);
insert into VOCABULARY_WORDS(vocabulary, word) values(2, 117);
insert into VOCABULARY_WORDS(vocabulary, word) values(2, 118);
insert into VOCABULARY_WORDS(vocabulary, word) values(2, 119);
insert into VOCABULARY_WORDS(vocabulary, word) values(2, 120);
insert into VOCABULARY_WORDS(vocabulary, word) values(2, 121);
insert into VOCABULARY_WORDS(vocabulary, word) values(2, 122);
insert into VOCABULARY_WORDS(vocabulary, word) values(2, 123);
insert into VOCABULARY_WORDS(vocabulary, word) values(2, 124);
insert into VOCABULARY_WORDS(vocabulary, word) values(2, 125);
insert into VOCABULARY_WORDS(vocabulary, word) values(2, 126);
insert into VOCABULARY_WORDS(vocabulary, word) values(2, 127);
commit;
