insert into words(russian, english, partofspeech, url)  values('анаконда', 'anaconda', 'NOUN', 'anaconda320.png');
insert into words(russian, english, partofspeech, url)  values('антилопа', 'antelope', 'NOUN', 'antelope320.png');
insert into words(russian, english, partofspeech, url)  values('бабуин', 'baboon', 'NOUN', 'baboon320.png');
insert into words(russian, english, partofspeech, url)  values('баран', 'ram', 'NOUN', 'ram320.png');
insert into words(russian, english, partofspeech, url)  values('барсук', 'badger', 'NOUN', 'badger320.png');
insert into words(russian, english, partofspeech, url)  values('белка', 'squirrel', 'NOUN', 'squirrel320.png');
insert into words(russian, english, partofspeech, url)  values('бобр', 'beaver', 'NOUN', 'beaver320.png');
insert into words(russian, english, partofspeech, url)  values('боров', 'boar', 'NOUN', 'boar320.png');
insert into words(russian, english, partofspeech, url)  values('бурундук', 'chipmunk', 'NOUN', 'chipmunk320.png');
insert into words(russian, english, partofspeech, url)  values('бык', 'bull, ox', 'NOUN', 'bull320.png');
insert into words(russian, english, partofspeech, url)  values('варан', 'monitor lizard', 'NOUN', 'monitorlizard320.png');
insert into words(russian, english, partofspeech, url)  values('верблюд', 'camel', 'NOUN', 'camel320.png');
insert into words(russian, english, partofspeech, url)  values('волк', 'wolf', 'NOUN', 'wolf320.png');
insert into words(russian, english, partofspeech, url)  values('выдра', 'otter', 'NOUN', 'otter320.png');
insert into words(russian, english, partofspeech, url)  values('выхухоль', 'desman, muskrat', 'NOUN', 'desman320.png');
insert into words(russian, english, partofspeech, url)  values('гадюка', 'adder, viper', 'NOUN', 'adder320.png');
insert into words(russian, english, partofspeech, url)  values('газель', 'gazelle', 'NOUN', 'gazelle320.png');
insert into words(russian, english, partofspeech, url)  values('геккон', 'gecko', 'NOUN', 'gecko320.png');
insert into words(russian, english, partofspeech, url)  values('гепард', 'cheetah', 'NOUN', 'cheetah320.png');
insert into words(russian, english, partofspeech, url)  values('гиббон', 'gibbon', 'NOUN', 'gibbon320.png');
insert into words(russian, english, partofspeech, url)  values('гиена', 'hyena', 'NOUN', 'hyena320.png');
insert into words(russian, english, partofspeech, url)  values('горилла', 'gorialla', 'NOUN', 'gorialla320.png');
insert into words(russian, english, partofspeech, url)  values('дельфин', 'dolphin', 'NOUN', 'dolphin320.png');
insert into words(russian, english, partofspeech, url)  values('дикобраз', 'porcupine', 'NOUN', 'porcupine320.png');
insert into words(russian, english, partofspeech, url)  values('еж', 'hedgehog', 'NOUN', 'hedgehog320.png');
insert into words(russian, english, partofspeech, url)  values('енот', 'raccoon', 'NOUN', 'raccoon320.png');
insert into words(russian, english, partofspeech, url)  values('жаба', 'toad', 'NOUN', 'toad320.png');
insert into words(russian, english, partofspeech, url)  values('жеребенок', 'foal', 'NOUN', 'foal320.png');
insert into words(russian, english, partofspeech, url)  values('жеребец', 'stallion', 'NOUN', 'stallion320.png');
insert into words(russian, english, partofspeech, url)  values('жираф', 'giraffe', 'NOUN', 'giraffe320.png');
insert into words(russian, english, partofspeech, url)  values('заяц', 'hare', 'NOUN', 'hare320.png');
insert into words(russian, english, partofspeech, url)  values('зебра', 'zebra', 'NOUN', 'zebra320.png');
insert into words(russian, english, partofspeech, url)  values('зубр', 'aurochs', 'NOUN', 'aurochs320.png');
insert into words(russian, english, partofspeech, url)  values('игуана', 'iguana', 'NOUN', 'iguana320.png');
insert into words(russian, english, partofspeech, url)  values('кабан', 'wild boar', 'NOUN', 'wildboar320.png');
insert into words(russian, english, partofspeech, url)  values('кенгуру', 'kangaroo', 'NOUN', 'kangaroo320.png');
insert into words(russian, english, partofspeech, url)  values('кит', 'whale', 'NOUN', 'whale320.png');
insert into words(russian, english, partofspeech, url)  values('коала', 'koala', 'NOUN', 'koala320.png');
insert into words(russian, english, partofspeech, url)  values('кобра', 'cobra', 'NOUN', 'cobra320.png');
insert into words(russian, english, partofspeech, url)  values('кобыла', 'mare', 'NOUN', 'mare320.png');
insert into words(russian, english, partofspeech, url)  values('коза', 'goat', 'NOUN', 'goat320.png');
insert into words(russian, english, partofspeech, url)  values('козел', 'billy-goat', 'NOUN', 'billygoat320.png');
insert into words(russian, english, partofspeech, url)  values('козленок', 'kid, goatling', 'NOUN', 'goatling320.png');
insert into words(russian, english, partofspeech, url)  values('корова', 'cow', 'NOUN', 'cow320.png');
insert into words(russian, english, partofspeech, url)  values('котенок', 'kitten', 'NOUN', 'kitten320.png');
insert into words(russian, english, partofspeech, url)  values('кошка', 'cat', 'NOUN', 'cat320.png');
insert into words(russian, english, partofspeech, url)  values('крокодил', 'crocodile', 'NOUN', 'crocodile320.png');
insert into words(russian, english, partofspeech, url)  values('кролик', 'rabbit', 'NOUN', 'rabbit320.png');
insert into words(russian, english, partofspeech, url)  values('крот', 'mole', 'NOUN', 'mole320.png');
insert into words(russian, english, partofspeech, url)  values('крыса', 'rat', 'NOUN', 'rat320.png');
insert into words(russian, english, partofspeech, url)  values('куница', 'marten', 'NOUN', 'marten320.png');
insert into words(russian, english, partofspeech, url)  values('лама', 'lama', 'NOUN', 'lama320.png');
insert into words(russian, english, partofspeech, url)  values('ласка', 'weasel', 'NOUN', 'weasel320.png');
insert into words(russian, english, partofspeech, url)  values('лев', 'lion', 'NOUN', 'lion320.png');
insert into words(russian, english, partofspeech, url)  values('ленивец', 'sloth', 'NOUN', 'sloth320.png');
insert into words(russian, english, partofspeech, url)  values('леопард', 'leopard', 'NOUN', 'leopard320.png');
insert into words(russian, english, partofspeech, url)  values('летучая мышь', 'bat', 'NOUN', 'bat320.png');
insert into words(russian, english, partofspeech, url)  values('лисица', 'fox', 'NOUN', 'fox320.png');
insert into words(russian, english, partofspeech, url)  values('лось', 'elk', 'NOUN', 'elk320.png');
insert into words(russian, english, partofspeech, url)  values('лошадь', 'horse', 'NOUN', 'horse320.png');
insert into words(russian, english, partofspeech, url)  values('лягушка', 'frog', 'NOUN', 'frog320.png');
insert into words(russian, english, partofspeech, url)  values('макака', 'macaque', 'NOUN', 'macaque320.png');
insert into words(russian, english, partofspeech, url)  values('манул', 'manul', 'NOUN', 'manul320.png');
insert into words(russian, english, partofspeech, url)  values('мартышка', 'mammoset', 'NOUN', 'mammoset320.png');
insert into words(russian, english, partofspeech, url)  values('медведь', 'bear', 'NOUN', 'bear320.png');
insert into words(russian, english, partofspeech, url)  values('морж', 'walrus', 'NOUN', 'walrus320.png');
insert into words(russian, english, partofspeech, url)  values('морская свинка', 'guinea pig', 'NOUN', 'guineapig320.png');
insert into words(russian, english, partofspeech, url)  values('муравьед', 'anteater', 'NOUN', 'anteater320.png');
insert into words(russian, english, partofspeech, url)  values('мышь', 'mouse', 'NOUN', 'mouse320.png');
insert into words(russian, english, partofspeech, url)  values('носорог', 'rhinoceros', 'NOUN', 'rhinoceros320.png');
insert into words(russian, english, partofspeech, url)  values('обезьяна', 'monkey, ape', 'NOUN', 'ape320.png');
insert into words(russian, english, partofspeech, url)  values('овца', 'sheep', 'NOUN', 'sheep320.png');
insert into words(russian, english, partofspeech, url)  values('олень', 'deer', 'NOUN', 'deer320.png');
insert into words(russian, english, partofspeech, url)  values('осел', 'donkey', 'NOUN', 'donkey320.png');
insert into words(russian, english, partofspeech, url)  values('пантера', 'panther', 'NOUN', 'panther320.png');
insert into words(russian, english, partofspeech, url)  values('пони', 'pony', 'NOUN', 'pony320.png');
insert into words(russian, english, partofspeech, url)  values('поросенок', 'piglet', 'NOUN', 'piglet320.png');
insert into words(russian, english, partofspeech, url)  values('пума', 'cougar', 'NOUN', 'cougar320.png');
insert into words(russian, english, partofspeech, url)  values('росомаха', 'wolverine, glutton', 'NOUN', 'wolverine320.png');
insert into words(russian, english, partofspeech, url)  values('рысь', 'lynx', 'NOUN', 'lynx320.png');
insert into words(russian, english, partofspeech, url)  values('свиноматка', 'sow', 'NOUN', 'sow320.png');
insert into words(russian, english, partofspeech, url)  values('свинья', 'pig', 'NOUN', 'pig320.png');
insert into words(russian, english, partofspeech, url)  values('серна', 'chamois', 'NOUN', 'chamois320.png');
insert into words(russian, english, partofspeech, url)  values('скунс', 'skunk', 'NOUN', 'skunk320.png');
insert into words(russian, english, partofspeech, url)  values('слон', 'elephant', 'NOUN', 'elephant320.png');
insert into words(russian, english, partofspeech, url)  values('собака', 'dog', 'NOUN', 'dog320.png');
insert into words(russian, english, partofspeech, url)  values('соболь', 'sable', 'NOUN', 'sable320.png');
insert into words(russian, english, partofspeech, url)  values('сурок', 'marmot', 'NOUN', 'marmot320.png');
insert into words(russian, english, partofspeech, url)  values('теленок', 'calf', 'NOUN', 'calf320.png');
insert into words(russian, english, partofspeech, url)  values('тигр', 'tiger', 'NOUN', 'tiger320.png');
insert into words(russian, english, partofspeech, url)  values('тюлень', 'seal', 'NOUN', 'seal320.png');
insert into words(russian, english, partofspeech, url)  values('удав', 'boa', 'NOUN', 'boa320.png');
insert into words(russian, english, partofspeech, url)  values('хомяк', 'hamster', 'NOUN', 'hamster320.png');
insert into words(russian, english, partofspeech, url)  values('хорек', 'ferret', 'NOUN', 'ferret320.png');
insert into words(russian, english, partofspeech, url)  values('черепаха сухопутная', 'tortoise', 'NOUN', 'tortoise320.png');
insert into words(russian, english, partofspeech, url)  values('черепаха водная', 'turtle', 'NOUN', 'turtle320.png');
insert into words(russian, english, partofspeech, url)  values('шимпанзе', 'chimpanzee', 'NOUN', 'chimpanzee320.png');
insert into words(russian, english, partofspeech, url)  values('щенок', 'puppy', 'NOUN', 'puppy320.png');
insert into words(russian, english, partofspeech, url)  values('ягненок', 'lamb', 'NOUN', 'lamb320.png');
insert into words(russian, english, partofspeech, url)  values('ягуар', 'jaguar', 'NOUN', 'jaguar320.png');
insert into words(russian, english, partofspeech, url)  values('ящерица', 'lizard', 'NOUN', 'lizard320.png');
commit;

insert into VOCABULARY_WORDS(vocabulary, word) values(3, 128);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 129);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 130);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 131);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 132);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 133);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 134);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 135);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 136);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 137);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 138);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 139);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 140);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 141);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 142);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 143);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 144);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 145);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 146);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 147);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 148);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 149);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 150);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 151);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 152);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 153);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 154);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 155);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 156);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 157);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 158);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 159);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 160);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 161);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 162);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 163);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 164);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 165);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 166);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 167);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 168);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 169);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 170);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 171);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 172);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 173);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 174);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 175);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 176);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 177);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 178);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 179);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 180);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 181);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 182);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 183);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 184);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 185);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 186);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 187);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 188);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 189);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 190);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 191);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 192);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 193);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 194);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 195);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 196);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 197);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 198);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 199);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 200);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 201);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 202);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 203);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 204);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 205);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 206);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 207);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 208);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 209);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 210);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 211);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 212);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 213);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 214);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 215);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 216);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 217);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 218);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 219);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 220);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 221);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 222);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 223);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 224);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 225);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 226);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 227);
insert into VOCABULARY_WORDS(vocabulary, word) values(3, 228);
commit;
